name: CI

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main, feature/*]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run backend tests
        run: |
          if [ -f "backend/server/test_backend.py" ]; then
            python -m unittest discover backend/server
          fi

      - name: Run extension tests
        run: |
          if [ -f "test_mcp.js" ]; then
            npm test
          fi

      - name: Lint Python
        run: |
          pip install flake8
          flake8 backend || true

      - name: Lint JS/TS
        run: |
          npm run lint || true 