name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Node dependencies
        run: |
          npm install
      - name: Run backend tests (pytest)
        run: |
          pytest backend/server
      - name: Run extension tests (mocha)
        run: |
          npm test
      - name: Build VSIX package
        run: |
          npm install -g @vscode/vsce
          vsce package 